api = "0.7"

[buildpack]
  description = "A buildpack for starting PHP app server start commands"
  homepage = "https://github.com/initializ-buildpacks/php-start"
  id = "initializ-buildpacks/php-start"
  keywords = ["php", "httpd", "nginx"]
  name = "Initializ Buildpack for PHP Start"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/php-start/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/procmgr-binary", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
